name: Branch Name Validation

on:
  pull_request:
    branches:
      - '*'

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate Branch Name
        run: |
          if [[ ! "${{ github.head_ref }}" =~ ^(feature|release|hotfix)/.*$ ]]; then
            echo "❌ Invalid branch name: ${{ github.head_ref }}"
            echo "Branch names must start with 'feature/', 'release/', or 'hotfix/'." >&2
            exit 1
          else
            echo "✅ Valid branch name: ${{ github.head_ref }}"
          fi
      
