name: PR Lint

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]
    branches: [main]

  workflow_dispatch:

jobs:
  pr-lint:
    name: Skip PR title and commit message validation
    runs-on: ubuntu-latest
    steps:
      - name: No Validation
        run: |
          echo "Skipping PR title and commit message validation."

