name: PR Lint

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  pr-lint:
    runs-on: ubuntu-latest

    steps:
      # Validate Branch Name
      - name: Validate Branch Name
        run: |
          if [[ ! "${{ github.head_ref }}" =~ ^(feature|hotfix|release)/[a-z]+-\d+$ ]]; then
            echo "❌ Invalid branch name: ${{ github.head_ref }}"
            echo "Branch names must follow the format 'feature/<ticket-number>', 'hotfix/<ticket-number>', or 'release/<ticket-number>' (e.g., 'feature/abc-300')." >&2
            exit 1
          else
            echo "✅ Valid branch name: ${{ github.head_ref }}"
          fi

      # PR Title Linter
      - name: PR Title Linter
        uses: morrisoncole/pr-lint-action@v1.7.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title-regex: '^\[[a-z]+-\d+\]\s+(Add|Remove|Change|Breaking Change|Fix|Release)\s+.+$'
          on-failed-regex-fail-action: true
          on-failed-regex-create-review: true
          on-failed-regex-request-changes: false
          on-failed-regex-comment: |
            The PR title should follow this format: 
            `[ticket-id] {Add|Remove|Change|Breaking Change|Fix|Release} The rest of the title`.
            Please ensure the title starts with a ticket ID like `[abc-300]` and is followed by an action (e.g., `Add`, `Change`, etc.) and a descriptive message.
          on-succeeded-regex-dismiss-review-comment: "Awesome! The PR title is correct and matches the format. Success!"

