name: PR Lint

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  pr-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Validate Branch Name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          if [[ ! "$BRANCH_NAME" =~ ^(feature|hotfix|release)/[a-zA-Z0-9-_]+-[0-9]+$ && ! "$BRANCH_NAME" =~ ^[a-zA-Z0-9-_]+-[0-9]+/(feature|hotfix|release)$ ]]; then
            echo "❌ Invalid branch name: $BRANCH_NAME"
            echo "Branch names must follow one of these formats:"
            echo "- feature/<ticket-number> (e.g., feature/abc-300)"
            echo "- hotfix/<ticket-number> (e.g., hotfix/abc-300)"
            echo "- release/<ticket-number> (e.g., release/aav-222)"
            echo "- <ticket-number>/feature (e.g., abc-300/feature)"
            echo "- <ticket-number>/hotfix (e.g., abc-300/hotfix)"
            echo "- <ticket-number>/release (e.g., aav-222/release)"
            exit 1
          else
            echo "✅ Valid branch name: $BRANCH_NAME"
          fi

      - name: PR Title Linter
        uses: morrisoncole/pr-lint-action@v1.7.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title-regex: '^(\[(\w+-\d+)\]\s*)+(Add|Remove|Change|Breaking Change|Fix|Release) .+$'
          on-failed-regex-fail-action: true
          on-failed-regex-create-review: true
          on-failed-regex-request-changes: false
          on-failed-regex-comment: "The PR should follow this format: `[ABCD-123] {Add|Remove|Change|Breaking Change|Fix|Release} The rest of the title`"
